### PR TITLE
Fix MIDI CC input in AU wrapper.

### PR DESCRIPTION
**Pull request by olicash**
Params learned to MIDI CCs are not currently getting updated on CC input from host.

### CODE REVIEW

**Comment by scheffle** [comment]
@olicash , can you explain you fix in more detail, please. For me it works here without your fix.

**Comment by olicash** [comment]
Look at what happens if the plug-in receives a MIDI CC message.  We hit `case kController:` and grab the CC number and value.  We don't assign anything to `pid`, which remains set to kNoParamId.  Then after the switch we inter the `if (prgChange || cn >= 0)` block but we don't look up whether the CC is mapped to anything in `midiMappingCache` because that is predicated on `if (pid != kNoParamId...`, where I believe it should be `if (pid == kNoParamId...`.  Hopefully that makes sense?

**Comment by scheffle** [comment]
Thanks for the heads up! I actually had this fix already on my machine when I was testing. We'll definitely add this change to the next SDK update.

**Comment by scheffle** [comment]
This is now fixed with VST SDK 3.7.13

**Pull request closed without merging**
